language: python
sudo: false
python:
- '2.7'
- '3.6'
env:
- TOXENV=py-test

matrix:
  include:
    - python: '2.7'
      env: TEST_SUITE=testing/runtests_travis.py
    - python: '3.6'
      env: TEST_SUITE=testing/runtests_travis.py
cache:
  files:
  - $HOME/.pip/cache
  - $Home/.cache/pip

notifications:
   slack: sekomy:FkxfwQ5tMIOzvoqGxOmhhdp2
install: pip install tox

script:
- python $TEST_SUITE
