language: python
sudo: false
python:
- '2.7'
- '3.6'
env:
- TOXENV=py-test

matrix:
  include:
    - python: '2.7'
      env: TEST_SUITE=suite_2_7
    - python: '3.6'
      env: TEST_SUITE=suite_3_6
cache:
  files:
  - $HOME/.pip/cache
  - $Home/.cache/pip

notifications:
   slack: sekomy:FkxfwQ5tMIOzvoqGxOmhhdp2
install: pip install tox

script:
- python testing/runtests_travis.py $TEST_SUITE
